<?php

namespace Pay\Controller;

use Common\Controller\HomebaseController;

/**
 * 随行付支付
 * Class BanksxfController
 * @package Pay\Controller
 */
class BanksxfController extends HomebaseController
{
    protected $mode;
    protected $price;
    protected $remark;
    protected $subject;
    protected $cate_id;
    protected $checker_id;
    protected $jmt_remark;
    protected $paystyle_id;
    private $pay_model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->pay_model = M('pay');

    }

    public function qr_weixipay()
    {
        //这里直接获得openid;
        if (strpos($_SERVER['HTTP_USER_AGENT'], 'MicroMessenger') !== false) {
            $id = I("id");
            $merchant = M("merchants_cate")->where("id=$id")->find();
            $openid = get_wx_openid();
            $this->getOffer($merchant, $openid);
            $this->assign('openid', $openid);
            $this->assign("merchant", $merchant);
            $this->assign('seller_id', I('id'));
            $this->display();
            die;
        }
    }


    public function wx_pay()
    {
        // 先获取openid
        if (I("seller_id") == "") {
            $sub_openid = get_wx_openid();
            $this->mode = 1;
            $this->cate_id = I("id");
            $cate_info = get_cate_info($this->cate_id);
            $this->checker_id = I("checker_id");
        } else {
            $sub_openid = I('openid');
            $this->mode = 0;
            $this->cate_id = I('seller_id');
            $cate_info = get_cate_info($this->cate_id);
            $this->checker_id = $cate_info['checker_id'];
        }
        $this->remark = I('order_sn', getRemark());
        if($this->pay_model->where(array('remark'=>  $this->remark))->find()){
            $this->alert_err("订单已存在");
        }
        $merchant_id = $cate_info['merchant_id'];
        $this->get_costomer_id($sub_openid, $merchant_id);  // 获取会员ID

        $this->price = I('price');
        $this->jmt_remark = I('memo','')?:I("jmt_remark",'');
        $this->subject = $cate_info['jianchen'];
        $this->paystyle_id = 1;

        $db_res = $this->add_db($merchant_id);
        if($db_res){
            // 请求服务器获取js支付参数
            $res_arr = $this->wx_jspay($sub_openid, $this->price);
            // 判断返回结果
            if ($this->check_sign($res_arr)) {
                if ($res_arr['resp_code'] == 0 && $res_arr['result_code'] == 0) {
                    $body = $res_arr['jspay_info'];
                    $this->assign('body', $body);
                    $this->assign('price', $this->price);
                    $this->assign('openid', $sub_openid);
                    $this->assign('remark', $this->remark);
                    $this->assign('mid', $cate_info['merchant_id']);
                    $this->display(":wx_pay");
                } else {
                    $this->alert_err($res_arr['error_msg']);
                }
            } else {
                $this->alert_err('签名异常');
            }
        } else {
            $this->alert_err();
        }
    }

    private function wx_jspay()
    {
        $sxfModel = D('Banksxf');
        $sxfModel->setParameters('');
        $sxfModel->setParameters('');
        $sxfModel->setParameters('');
        $sxfModel->setParameters('');
        $sxfModel->setParameters('');
        $sxfModel->setParameters('');

        return $sxfModel->getPayInfo();
    }

    private function add_db($merchant_id)
    {
        $payModel = D("pay");
        $payModel->setParameters('status', 0);
        $payModel->setParameters('mode', $this->mode);
        $payModel->setParameters('bank', $this->bank);
        $payModel->setParameters('price', $this->price);
        $payModel->setParameters('remark', $this->remark);
        $payModel->setParameters('cost_rate', $this->rate);
        $payModel->setParameters('cate_id', $this->cate_id);
        $payModel->setParameters('subject', $this->subject);
        $payModel->setParameters('merchant_id', $merchant_id);
        $payModel->setParameters('order_id', $this->order_id?:0);
        $payModel->setParameters('jmt_remark', $this->jmt_remark);
        $payModel->setParameters('checker_id', $this->checker_id);
        $payModel->setParameters('customer_id', $this->customer_id);
        $payModel->setParameters('paystyle_id', $this->paystyle_id);

        return $payModel->add_pay();
    }

    function alert_err($msg = '网络错误，请稍后再试')
    {
        $this->assign('err_msg',"$msg");
        $this->display(":error");
        exit;
    }
}