<?php
return array (
  'app' => 'Screen',
  'model' => 'Index',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '双屏收银',
  'icon' => 'youtube-play',
  'remark' => '',
  'listorder' => '99',
  'children' => 
  array (
    array (
      'app' => 'Screen',
      'model' => 'Posadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '收银机管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Screen',
          'model' => 'Posadmin',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加收银机',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Screen',
          'model' => 'Posadmin',
          'action' => 'change_status',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '改变审核状态',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'screen',
      'model' => 'Memadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '会员管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Screen',
      'model' => 'Couponadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '优惠卷管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Screen',
      'model' => 'Memcouponadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '优惠券领券列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);