<?php
return array (
  'app' => 'Admin',
  'model' => 'Agent',
  'action' => 'index',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '代理商后台',
  'icon' => '',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Merchants',
      'model' => 'AdminAgent',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '代理商列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Merchants',
          'model' => 'AdminAgent',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加代理商',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Merchants',
              'model' => 'AdminAgent',
              'action' => 'add_user',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加用户',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminAgent',
          'action' => 'detail',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '详情',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminAgent',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '修改',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminAgent',
          'action' => 'exchangeSatatus',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '改变审核状态',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Agent',
      'action' => 'agentmerchant',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => 'Api商户管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);