<?php
return array (
  'app' => 'Message',
  'model' => '0',
  'action' => '0',
  'data' => '0',
  'type' => '1',
  'status' => '1',
  'name' => '消息管理',
  'icon' => 'bell',
  'remark' => 'bell-slash',
  'listorder' => '99',
  'children' => 
  array (
    array (
      'app' => 'Message',
      'model' => 'AdminSystem',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '系统消息',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Message',
          'model' => 'AdminSystem',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加消息',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Message',
          'model' => 'AdminSystem',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Message',
          'model' => 'AdminSystem',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Message',
      'model' => 'AdminSms',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => ' 手机短信',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Merchants',
      'model' => 'Msinto',
      'action' => 'sms_index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '短信验证码',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);