<?php
return array (
  'app' => 'Ad',
  'model' => 'index',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '广告管理',
  'icon' => 'newspaper-o',
  'remark' => '',
  'listorder' => '99',
  'children' => 
  array (
    array (
      'app' => 'Ad',
      'model' => 'Pictureadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '图片广告管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Ad',
          'model' => 'Pictureadmin',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '新增图片广告',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Ad',
              'model' => 'Pictureadmin',
              'action' => 'add_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Ad',
          'model' => 'Pictureadmin',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Ad',
              'model' => 'Pictureadmin',
              'action' => 'edit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交编辑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Ad',
          'model' => 'Pictureadmin',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Ad',
          'model' => 'Pictureadmin',
          'action' => 'change_status',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '改变状态',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Ad',
      'model' => 'Playeradmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '视频管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);