<?php
return array (
  'app' => 'Merchants',
  'model' => 'AdminIndex',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '商户管理',
  'icon' => 'user',
  'remark' => '',
  'listorder' => '1',
  'children' => 
  array (
    array (
      'app' => 'Material',
      'model' => '0',
      'action' => '0',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '物料管理',
      'icon' => 'qrcode',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Material',
          'model' => 'AdminMaterialcate',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '物料分类',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Material',
          'model' => 'AdminMaterial',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '物料列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Merchants',
      'model' => 'AdminIndex',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '商户列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Merchants',
          'model' => 'AdminIndex',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加商户',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminIndex',
          'action' => 'update_pwd',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '修改手机号',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminIndex',
          'action' => 'add_user',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加用户',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'Uploadify',
          'action' => 'upload',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '上传图片',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'Ueditor',
          'action' => 'imageUp',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '上传路径',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminIndex',
          'action' => 'exchangeSatatus',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '改变审核状态',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminInto',
          'action' => 'upload_hdmpay',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '保存进件资料',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'Adminzsinto',
          'action' => 'zsshow',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '招商进件',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Pay',
          'model' => 'Barcodezsbank',
          'action' => 'mchpaykey',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '招商审核',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'Adminzsinto',
          'action' => 'upload_into',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '招商图片上传',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Pay',
          'model' => 'Barcodezsbank',
          'action' => 'mchinlet',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '招商进件按钮',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Pay',
          'model' => 'Barcodezsbank',
          'action' => 'mchinlet_notify',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '招商进件审核加激活',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'Adminzsinto',
          'action' => 'upload_zspay',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '招商保存进件资料',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminIndex',
          'action' => 'cate_edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '台签设置',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminIndex',
          'action' => 'checker_edit_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '台签设置提交',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminIndex',
          'action' => 'cate_edit1',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '台签设置1',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminIndex',
          'action' => 'checker_edit_post1',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '商户台签提交1',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminIndex',
          'action' => 'ali_change_bank',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '支付宝切换银行',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminIndex',
          'action' => 'wx_change_bank',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '微信切换银行',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Merchants',
      'model' => 'AdminService',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '服务开通',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'admin',
      'model' => 'index',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '进件列表汇总',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Merchants',
          'model' => 'Upwzadmin',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '商户微众进件列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Merchants',
              'model' => 'upwzadmin',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '1',
              'name' => '添加进件',
              'icon' => '',
              'remark' => 'g=merchants&amp;m=upwzadmin&amp;a=index',
              'listorder' => '0',
            ),
            array (
              'app' => 'Merchants',
              'model' => 'Upwzadmin',
              'action' => 'blind_cate',
              'data' => '',
              'type' => '1',
              'status' => '1',
              'name' => '绑定',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Merchants',
          'model' => 'Upweicanadmin',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '围餐进件列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'msinto',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '民生进件列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Merchants',
              'model' => 'AdminInto',
              'action' => 'check_hdmpay',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '编辑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Merchants',
              'model' => 'adminInto',
              'action' => 'check_into',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '审核',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Merchants',
          'model' => 'Adminzsinto',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '招商进件列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'QianFangadmin',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '钱方进件列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'Adminmsday',
          'action' => 'jn_list',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '济南民生进件列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'Alikoubei',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '支付宝口碑商户',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Merchants',
              'model' => 'Alikoubei',
              'action' => 'add',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Merchants',
          'model' => 'HengfengBank',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '恒丰银行进件',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'Xybankinto',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '兴业进件列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Merchants',
      'model' => 'AdminIndex',
      'action' => 'ab',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '商户',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Merchants',
          'model' => 'AdminIndex',
          'action' => 'detail',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '详情',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'AdminIndex',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '修改',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Pay',
          'model' => 'Cateadmin',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加二维码',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Merchants',
      'model' => 'adminUser',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '用户',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Merchants',
      'model' => 'AdminRole',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '角色',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Merchants',
      'model' => 'AdminWzbank',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '0',
      'name' => '微众支持银行列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Merchants',
      'model' => 'Cateadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '商户台签列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Merchants',
          'model' => 'cateadmin',
          'action' => 'add',
          'data' => '0',
          'type' => '1',
          'status' => '0',
          'name' => '添加台签',
          'icon' => '0',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'Cateadmin',
          'action' => 'change_status',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '改变状态',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'Cateadmin',
          'action' => 'detail',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => ' 台签详情',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Merchants',
          'model' => 'Cateadmin',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
  ),
);