<?php
return array (
  'app' => 'Pay',
  'model' => '0',
  'action' => '0',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '流水查看(报表)',
  'icon' => 'bar-chart',
  'remark' => '支付窗口数据和支付管理',
  'listorder' => '4',
  'children' => 
  array (
    array (
      'app' => 'Pay',
      'model' => 'Agentadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '代理商流水汇总',
      'icon' => '',
      'remark' => '代理商下的商户收支',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Pay',
          'model' => 'Agentadmin',
          'action' => 'get_detail',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '流水详情',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Pay',
              'model' => 'Agentadmin',
              'action' => 'change_status',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '改变状态',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Pay',
          'model' => 'Agentadmin',
          'action' => 'upload_excel',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '导出excel表格',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Pay',
      'model' => 'Indexadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '支付数据统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Pay',
      'model' => 'Cashadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '商户充值列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Pay',
      'model' => 'Chartadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '昨日流水(报表)',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Pay',
      'model' => 'Contentadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '支付流水列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Pay',
      'model' => 'Shopadmin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '商户流水汇总',
      'icon' => '',
      'remark' => '商户每日收支查询',
      'listorder' => '0',
    ),
  ),
);