<?php
return array (
  'app' => 'Goods',
  'model' => '0',
  'action' => '0',
  'data' => '0',
  'type' => '1',
  'status' => '1',
  'name' => '商品模块',
  'icon' => 'shopping-cart',
  'remark' => '',
  'listorder' => '99',
  'children' => 
  array (
    array (
      'app' => 'Goods',
      'model' => 'AdminCategory',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '商品分类',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Goods',
      'model' => 'AdminCategory',
      'action' => 'add',
      'data' => '',
      'type' => '1',
      'status' => '0',
      'name' => '分类添加',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Goods',
      'model' => 'AdminCategory',
      'action' => 'edit',
      'data' => '',
      'type' => '1',
      'status' => '0',
      'name' => '分类修改',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Goods',
      'model' => 'AdminCategory',
      'action' => 'delete',
      'data' => '',
      'type' => '1',
      'status' => '0',
      'name' => '分类删除',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Goods',
      'model' => 'AdminGoods',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '商品列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);